#!/usr/bin/env bash
# A bash script that will display information about subdomains.

subdomain_info () {
    print_ip=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $print_ip" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" -eq 2 ]
then
  subdomain_info "$1" "$2"
else
  subdomain_info "$1" "www"
  subdomain_info "$1" "lb-01"
  subdomain_info "$1" "web-01"
  subdomain_info "$1" "web-02"
fi
