#!/usr/bin/env bash
# This script configures Ubuntu and 2 server
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" | tee /var/www/html/index.nginx-debian.html
n_string="listen 80 default_server;\\n\\tlocation \/redirect_me {\\n\\t\\treturn 301 https:\/\/www.youtube.com\/;\\n\\t}"
sed -i "s/listen 80 default_server;/$n_string/" /etc/nginx/sites-enabled/default
n_string2="http {\\n\\tadd_header X-Served-By \"$HOSTNAME\";"
sed -i "s/http {/$n_string2/" /etc/nginx/nginx.conf
service nginx start
