#!/usr/bin/env bash
# Bash script that displays Best School 10 times,
# but for the 9th iteration, displays Hi
i=0
while [ "$i" -lt 10 ]
do
	echo "Best School"
	if [ "$i" -eq 8 ]
	then
		echo "Hi"
	fi
	i=$((i + 1))
done
i=$i
