#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 20 and:
# displays 4 and then bad luck from china fir the 4th iteration,
# displays 9 and then bad luck from Japan for the 9th ite,
# displays 17 and then bad luck from Italy fot 17th ite
i=0
while [ "$i" -lt 20 ]
do
	echo "$i"
	case $i in 
		3)
		echo "bad luck from China"
		;;
		8)
		echo "bad luck from Japan"
		;;
		16)
		echo "bad luck from Italy"
		;;
	esac
	i=$((i + 1))
done
i=$i

